### ISSUE TITLE
How can include non-ascii character to fill up pdf form with netcore.

### ISSUE THREAD

**Issue by wcartayad** [kevbite/Kevsoft.PDFtk#18]
When the pdf form shows up, the non-ASCII characters are missing. 
Any suggestions?

**Comment by kevbite** [comment]
@wcartayad interesting, do you have a small sample you can share?

**Comment by wcartayad** [comment]
@kevbite  thanks for the response
By example, the name must be **Alejandro López Alvarez**
![image](https://user-images.githubusercontent.com/32780211/143566447-941880af-1d4d-41b8-a396-d74c216947c0.png)

That is an input of pdf form

**Comment by kevbite** [comment]
Just done a quick test and I can see it's not working correctly, however, it seems to be producing the correct xfdf file.

```xml
<?xml version="1.0" encoding="utf-8"?>
<xfdf xml:space="preserve" xmlns="http://ns.adobe.com/xfdf/">
    <fields>
        <field name="Given Name Text Box"><value>Alejandro López Alvarez</value>
        </field>
    </fields>
</xfdf>
```

I'll try to look into this further 👍

**Comment by wcartayad** [comment]
This happens to me on AWS EC with Linux; but local with windows 11, the same issue. 
The PDF was generated with Adobe Reader in Windows.

Also, I notice the field above, is a multiline field and it shows the no-ASCII characters. 
![image](https://user-images.githubusercontent.com/32780211/143656004-15261d13-b4e1-4da6-af86-2c8352b1db9d.png)

**Comment by kevbite** [comment]
@wcartayad is there any chance you can attach a blank version of that PDF or create one that doesn't work for you?

**Comment by wcartayad** [comment]
[FichaMatricula.pdf](https://github.com/kevbite/Kevsoft.PDFtk/files/7612577/FichaMatricula.pdf)
@kevbite here is a empty version.
Thanks for help

**Comment by kevbite** [comment]
Hey @wcartayad I think the problem is somewhere inside the PDF file as it's displaying the value correctly for some of the fields but not others:
![image](https://user-images.githubusercontent.com/5544715/143858961-05e547c6-1d35-4d56-945a-5e3fc11053a8.png)
![image](https://user-images.githubusercontent.com/5544715/143858984-f0397c45-c25b-4ec8-929a-ed2b3b5ad019.png)
Also if you do click in to them it then displays the correct value:
![image](https://user-images.githubusercontent.com/5544715/143859037-c6159e74-656e-4e6a-8dc7-5efc2c7e4a23.png)

Big stab in the dark but could it be the font that is being used within the PDF?

**Comment by wcartayad** [comment]
Thanks for the help;  I'll rebuild the pdf.

Thanks a lot
